
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 195382 bytes/channel
 *	Total Size: 1 * 195382 + 4 (header) = 195426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Josh\Documents\GT Fall 2017\CS 2261\Labs\Lab11\GameSong.wav
 *	Time-stamp: Mon Nov 20 15:50:38 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 195382

extern const unsigned char GameSong[195382];

#endif /* __GAMESONGH__ */
