
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 447027 bytes/channel
 *	Total Size: 1 * 447027 + 4 (header) = 447071 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Josh\Documents\GT Fall 2017\CS 2261\Labs\Lab11\TitleSong.wav
 *	Time-stamp: Mon Nov 20 15:50:43 2017
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 447027

extern const unsigned char TitleSong[447027];

#endif /* __TITLESONGH__ */
