
/**************************************************************
 *	
 *	cheeseCollected, 8 bit, 11025Hz,
 *	1 channel, 3208 bytes/channel
 *	Total Size: 1 * 3208 + 4 (header) = 3252 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\cheeseCollected.wav
 *	Time-stamp: Wed Nov 29 01:11:49 2017
 *	
 **************************************************************/

#ifndef __CHEESECOLLECTEDH__
#define __CHEESECOLLECTEDH__

#define CHEESECOLLECTEDFREQ 11025
#define CHEESECOLLECTEDLEN 3208

extern const unsigned char cheeseCollected[3208];

#endif /* __CHEESECOLLECTEDH__ */
