
/**************************************************************
 *	
 *	death, 8 bit, 44100Hz,
 *	1 channel, 324156 bytes/channel
 *	Total Size: 1 * 324156 + 4 (header) = 324200 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\death.wav
 *	Time-stamp: Tue Nov 28 20:59:11 2017
 *	
 **************************************************************/

#ifndef __DEATHH__
#define __DEATHH__

#define DEATHFREQ 44100
#define DEATHLEN 324156

extern const unsigned char death[324156];

#endif /* __DEATHH__ */
