
/**************************************************************
 *	
 *	musicGame, 8 bit, 11025Hz,
 *	1 channel, 342348 bytes/channel
 *	Total Size: 1 * 342348 + 4 (header) = 342392 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\musicGame.wav
 *	Time-stamp: Thu Nov 30 00:10:59 2017
 *	
 **************************************************************/

#ifndef __MUSICGAMEH__
#define __MUSICGAMEH__

#define MUSICGAMEFREQ 11025
#define MUSICGAMELEN 342348

extern const unsigned char musicGame[342348];

#endif /* __MUSICGAMEH__ */
