
/**************************************************************
 *	
 *	musicWin, 8 bit, 11025Hz,
 *	1 channel, 588000 bytes/channel
 *	Total Size: 1 * 588000 + 4 (header) = 588044 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\musicWin.wav
 *	Time-stamp: Tue Nov 28 20:37:54 2017
 *	
 **************************************************************/

#ifndef __MUSICWINH__
#define __MUSICWINH__

#define MUSICWINFREQ 11025
#define MUSICWINLEN 588000

extern const unsigned char musicWin[588000];

#endif /* __MUSICWINH__ */
