
/**************************************************************
 *	
 *	musicPause, 8 bit, 11025Hz,
 *	1 channel, 732739 bytes/channel
 *	Total Size: 1 * 732739 + 4 (header) = 732783 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\musicPause.wav
 *	Time-stamp: Tue Nov 28 20:37:58 2017
 *	
 **************************************************************/

#ifndef __MUSICPAUSEH__
#define __MUSICPAUSEH__

#define MUSICPAUSEFREQ 11025
#define MUSICPAUSELEN 732739

extern const unsigned char musicPause[732739];

#endif /* __MUSICPAUSEH__ */
