
/**************************************************************
 *	
 *	musicLose, 8 bit, 11025Hz,
 *	1 channel, 1750462 bytes/channel
 *	Total Size: 1 * 1750462 + 4 (header) = 1750506 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\musicLose.wav
 *	Time-stamp: Tue Nov 28 20:38:01 2017
 *	
 **************************************************************/

#ifndef __MUSICLOSEH__
#define __MUSICLOSEH__

#define MUSICLOSEFREQ 11025
#define MUSICLOSELEN 1750462

extern const unsigned char musicLose[1750462];

#endif /* __MUSICLOSEH__ */
