
/**************************************************************
 *	
 *	soundCat, 8 bit, 11025Hz,
 *	1 channel, 4716 bytes/channel
 *	Total Size: 1 * 4716 + 4 (header) = 4760 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\soundCat.wav
 *	Time-stamp: Thu Nov 30 19:25:06 2017
 *	
 **************************************************************/

#ifndef __SOUNDCATH__
#define __SOUNDCATH__

#define SOUNDCATFREQ 11025
#define SOUNDCATLEN 4716

extern const unsigned char soundCat[4716];

#endif /* __SOUNDCATH__ */
