
/**************************************************************
 *	
 *	soundClick, 8 bit, 11025Hz,
 *	1 channel, 11576 bytes/channel
 *	Total Size: 1 * 11576 + 4 (header) = 11620 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\soundClick.wav
 *	Time-stamp: Tue Nov 28 20:37:47 2017
 *	
 **************************************************************/

#ifndef __SOUNDCLICKH__
#define __SOUNDCLICKH__

#define SOUNDCLICKFREQ 11025
#define SOUNDCLICKLEN 11576

extern const unsigned char soundClick[11576];

#endif /* __SOUNDCLICKH__ */
