
/**************************************************************
 *	
 *	soundGun, 8 bit, 11025Hz,
 *	1 channel, 6616 bytes/channel
 *	Total Size: 1 * 6616 + 4 (header) = 6660 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Gatech\2017 Fall\CS 2261\Final\Music\soundGun.wav
 *	Time-stamp: Thu Nov 30 19:28:44 2017
 *	
 **************************************************************/

#ifndef __SOUNDGUNH__
#define __SOUNDGUNH__

#define SOUNDGUNFREQ 11025
#define SOUNDGUNLEN 6616

extern const unsigned char soundGun[6616];

#endif /* __SOUNDGUNH__ */
